services:   
  resumecreatorapi:
    image: resumecreatorapi
    container_name: resumecreatorapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5074:5074"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db


volumes:
  mongodb_data: 